name: Python Application

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
      uses: actions/checkout@v1

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: build dist
      run: |
        cd api/terminal
        pip3 install wheel
        python3.6 setup.py bdist_wheel
